[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Reporte HTML por defecto
addopts =
    --html=reports/report.html
    --self-contained-html
    -v
    --tb=short

# Marcadores personalizados
markers =
    login: tests de inicio de sesión
    cart: tests de carrito de compras
    api: tests de servicios web
    smoke: suite de smoke test
    regression: suite de regresión
    intentional_fail: caso con falla intencional para demo
